### ISSUE TITLE
Operating system licensing on RACI

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmware-service#1]
Should the RACI include who is responsible for Operating System licensing?

**Comment by delia-rusu** [comment]
Internal item https://github.ibm.com/VMWSolutions/tracker/issues/8547 opened.

**Comment by delia-rusu** [comment]
Internal issue https://github.ibm.com/VMWSolutions/tracker/issues/8547 was closed. Doc updates will be available with the next release.
