### ISSUE TITLE
Add an example for vcd org admin login 

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmware-service#10]
If you use a user e.g. "admin" you must add the org id e.g. "admin@8db98de2-7735-41f1-a487-64fcaefde250". This is not obvious.

**Comment by delia-rusu** [comment]
@skuronen can you please add the link to the topic this issue refers to?

@tlclarkibm FYI

**Comment by skuronen** [comment]
![image](https://github.com/ibm-cloud-docs/vmware-service/assets/27805477/4588a35c-cf16-431f-8c68-5cb885cec885)

https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-vcda-migrating-onprem

**Comment by tlclarkibm** [comment]
Doc update is complete and will be pushed to production with Feb Release (2/9).
https://test.cloud.ibm.com/docs/vmware-service?topic=vmware-service-vcda-migrating-onprem

**Comment by skuronen** [comment]
Looks good. Can be closed.
