### ISSUE TITLE
Redhat Openshift Outdated worker node

### ISSUE THREAD

**Issue by Tgmertens** [ibm-cloud-docs/vmware-service#11]
In a VPC cluster with IBM Kubernetes Service, what is the correct method to update an outdated worker node?

Should I update, replace, reload or resize or Update

**Comment by delia-rusu** [comment]
@Tgmertens can you please add the link to the topic this issue refers to?

@tlclarkibm FYI

**Comment by robw-one** [comment]
@Tgmertens @tlclarkibm @delia-rusu 
Is this Git targeted to the wrong IBM Cloud Service.  Should this issue be assigned to IBM Cloud Kubernetes (IKS)?
Here from, IBM Cloud VMware team, I don't think we can represent IKS.

**Comment by Tgmertens** [comment]
I can delete, 1 st time user

**Comment by delia-rusu** [comment]
Thank you @robw-one 

@Tgmertens no problem at all. You can open a doc issue for the IBM Cloud Kubernetes Service by using this link:  https://cloud.ibm.com/docs/containers?topic=containers-getting-started

If you're OK with this, please close this GH issue, thanks!

**Comment by Tgmertens** [comment]
Cant delete a file branch, I am a 1st time user Tom Mertens From: Delia RusuSent: Friday, February 2, 2024 9:12 AMTo: ibm-cloud-docs/vmware-serviceCc: Tgmertens; MentionSubject: Re: [ibm-cloud-docs/vmware-service] Redhat Openshift Outdated worker node (Issue #11) Thank you @***@***.*** no problem at all. You can open a doc issue for the IBM Cloud Kubernetes Service by using this link: https://cloud.ibm.com/docs/containers?topic=containers-getting-startedIf you're OK with this, please close this GH issue, thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
