### ISSUE TITLE
Reference to old service 

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmware-service#14]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-vcda-migrating-onprem

### What do you think needs to be updated?

`You can use VMware Cloud Director Availability (VCDA) to migrate your vCenter virtual machine (VM) workloads from on-premises and VMware vCenter Server® environments to IBM Cloud® for VMware Cloud Foundation as a Service...`

"VMware vCenter Server®" here seems to refer to an IBM offering "VCF for Classic". The same seems to be in the other VCDA related docs.  

### Anything else?

![image](https://github.com/user-attachments/assets/efae2182-f22d-4db8-bf6c-e790954d6ecc)

**Comment by Delia-Rusu1** [comment]
@TracyClark1 please take a look.

**Comment by Delia-Rusu1** [comment]
IBM offering name is updated; remaining references to "VMware vCenter Server" and "VMware vCenter" are referring to the VMware by Broadcom offering.
