### ISSUE TITLE
Storage description for multi Zone VMware as Service

### ISSUE THREAD

**Issue by dwarakanathprao** [ibm-cloud-docs/vmware-service#15]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-tenant-plan-deploy#tenant-plan-deploy-storage

### What do you think needs to be updated?

We need to provide proper update on VSAN storage options for VCFaaS for multi zone deployment. there is hardly any details available for multi zone deployment for VCFaaS. VMware as Service.  we also don't show case details of NFS as options, this needs to be corrected/.

### Anything else?

https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-tenant-plan-deploy#tenant-plan-deploy-storage. 
We need to provide proper update on VSAN storage options for VCFaaS for multi zone deployment. there is hardly any details available for multi zone deployment for VCFaaS. VMware as Service.  we also don't show case details of NFS as options, this needs to be corrected/.

**Comment by Delia-Rusu1** [comment]
@TracyClark1 please take a look.

**Comment by TracyClark1** [comment]
@Delia-Rusu1 updates have been pushed to production along with Dec release. You can close out this issue. Thank you!
https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-tenant-plan-deploy#tenant-plan-deploy-cluster-storage
