### ISSUE TITLE
Link directs to a test.cloud.ibm.com url

### ISSUE THREAD

**Issue by ShaunAndersonAZ** [ibm-cloud-docs/vmware-service#2]
From this page:
https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-shared-intro
The 'Operating VMware Shared' link redirects to https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-shared_vcd-ops-guide.

Removing the 'test' portion of the URL directs to the proper location.

**Comment by delia-rusu** [comment]
Link updated and will be published externally with the next release.
