### ISSUE TITLE
Link at bottom of page it pointed to test.cloud.ibm.com

### ISSUE THREAD

**Issue by bryanbuckland** [ibm-cloud-docs/vmware-service#3]
Page : https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-iam_vcd&interface=ui

Last link is referncing
https://test.cloud.ibm.com/docs/vmware-service?topic=vmware-service-iam&interface=ui

**Comment by delia-rusu** [comment]
Link updated and will be published externally with the next release.
