### ISSUE TITLE
Page not found issue in VMaaS documentation

### ISSUE THREAD

**Issue by andrewj2000** [ibm-cloud-docs/vmware-service#4]
On this page: https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-iam-integration in the Before you begin section, there are 2 links.  The first link returns a page not found: [Managing IAM access for VMware as a Service](https://cloud.ibm.com/docs/vmware-service?topic=vmware-service-iam&interface=ui)

**Comment by delia-rusu** [comment]
@tlclarkibm Please take a look, thanks!
