### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by andrewj2000** [ibm-cloud-docs/vmware-service#5]
In the VMwaaS docs, there are two pages:
- Accessing the VMware Cloud Director console
- VMware Cloud Director single sign-on with IBM Cloud IAM

I think the _Accessing_ page is a carry over from the VMware Shared documentation and should probably be removed or parts of its content added to the 2nd page, as the SSO with IAM is automatically done. The user is not required to set the vCD passwd as described in the _Accessing_ page.

Happy to provide more clarification if needed.

**Comment by delia-rusu** [comment]
@tlclarkibm can you please investigate? Thanks!

**Comment by tlclarkibm** [comment]
@andrewj2000 thank you for the feedback! I agree, I removed the "Accessing the VMware Cloud Director console" from the TOC. I did pull the intro over to also include in the [VMware Cloud Director single sign-on with IBM Cloud IAM ](https://test.cloud.ibm.com/docs/vmware-service?topic=vmware-service-iam-integration) topic.

This will be updated on public documentation for Ocracoke go live.

**Comment by delia-rusu** [comment]
@tlclarkibm is this complete? If yes, please close it, thanks!
