### ISSUE TITLE
Security descriptions

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmware-service#6]
This section needs rework.

Does this reflect multi-tenant correctly?

https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-architecture-workload-isolation-learning#architecture-workload-isolation-wkld

https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-architecture-workload-isolation-learning#architecture-workload-isolation-trust-zones

For example:

Typos... Akami. Odd sentences.

`These resources exist in IBM Cloud classic IaaS. Management interfaces are protected by networking appliance firewalls and the use of bastion hosts by the operations team. Management component connectivity to the workload plane takes place through networking appliances. Public connectivity to all public service interfaces is protected through Akami security. Customers access VMware Cloud Director and associated service portals by using the web UI from the public network. These interfaces are restricted and do not enable customers to transit further through the management plane network.`

What does broad mean? They do not have any access at all. 

`Management interfaces are protected by networking appliances firewalls. Customer workloads are allowed by VMware Cloud Director to attach only to restricted, separate NSX-T virtualized networks that are running as overlays on the classic IaaS network. Therefore, customer VMs do not have broad access to the Workload Plane management and storage networks. Their access is restricted by using NSX-T edge appliances. Customer workload connectivity to public takes place through NSX-T edge routers that are managed by the customer through a restricted VMware Cloud Director interface. Customer workload connectivity to private takes place through IBM-managed NSX-T edge routers that are configured to limit connectivity to well-known IBM Cloud private services.`

This section as a whole needs some work.

**Comment by delia-rusu** [comment]
@tlclarkibm please take a look, thanks!

**Comment by delia-rusu** [comment]
Updates completed: https://test.cloud.ibm.com/docs/vmware-service?topic=vmware-service-architecture-workload-isolation-learning#architecture-workload-isolation-trust-zones on the test environment.

Final review in progress.

**Comment by skuronen** [comment]
Looks good. This can be closed.
