### ISSUE TITLE
Customers do not have access to VMware Customer Connect

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmware-service#9]
`From VMware Customer Connect, download the VMware Cloud Director Availability On-premises Appliance .ova file to a server that has a network connection to the vCenter Server.`

What is the IBM Cloud process?

**Comment by delia-rusu** [comment]
@tlclarkibm FYI - Step 1 in https://test.cloud.ibm.com/docs/vmware-service?topic=vmware-service-vcda-migrating

**Comment by robw-one** [comment]
@skuronen what do you recommend as the Cloud process?  The only location I know of to obtain the VCDA on-prem ova from is VMware Customer Connect.  I'm not sure on any legal agreements and such for us to rehost but likely needs to be redirected to OM

**Comment by skuronen** [comment]
How many customers have VMware Customer Connect IDs? Normally they do not, as they buy this as a service from IBM Cloud. How do customers get update .mob files to update/upgrade NSX? Same thing.

So then shouldn't the simple process be raise a support ticket and they provide customers the file? If this is not legally ok, then we have a bigger issue.

**Comment by tlclarkibm** [comment]
Per Slack discussion note added to step 1: https://test.cloud.ibm.com/docs/vmware-service?topic=vmware-service-vcda-migrating
